services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    env_file:
      - .env
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/public/build
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
